substitutions:
  name: "esphome-presence-light-2024-7-1"

esphome:
  name: "$name"
  friendly_name: ESPHome - Presence + Light
  comment: ESP32-C3-MINI-1-N4 - Presence + Light Sensors V2024.7.1
  project:
    name: "RSVH.Presence_+_Light_Sensors"
    version: "2024.7.1"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: latest

packages:
  base_general: !include .general-config.yaml
  base_esp32: !include .esp32.yaml

wifi:
  # manual_ip:
  #   static_ip: 10.10.30.X
  #   gateway: 10.10.30.1
  #   subnet: 255.255.255.0

status_led:
  pin:
    number: GPIO2
    inverted: true

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: True

uart:
  id: uart_bus
  rx_pin: GPIO5
  tx_pin: GPIO4
  baud_rate: 115200

dfrobot_sen0395:

binary_sensor:
  - platform: dfrobot_sen0395
    name: mmWave UART
    id: mmwave_uart
    icon: mdi:motion-sensor
    device_class: motion

  - platform: gpio
    name: mmWave GPIO
    id: mmwave_gpio
    icon: mdi:motion-sensor
    device_class: motion
    pin:
      number: GPIO10
      mode: INPUT_PULLDOWN

switch:
  - platform: dfrobot_sen0395
    type: sensor_active
    name: SEN0395 Active
    icon: mdi:toggle-switch-off-outline

  - platform: dfrobot_sen0395
    type: turn_on_led
    name: SEN0395 LED
    icon: mdi:toggle-switch-off-outline

sensor:
  - platform: bh1750
    name: "Illuminance"
    icon: mdi:brightness-5
    address: 0x23
    update_interval: 1s

text_sensor:
  - platform: homeassistant
    name: Lights Woonkamer
    icon: mdi:lightbulb-on
    id: lights_woonkamer
    entity_id: light.verlichting_woonkamer
    internal: False

number:
  - platform: template
    name: Sensitivity
    id: sensitivity
    icon: mdi:tune-variant
    entity_category: config
    min_value: 1
    max_value: 9
    initial_value: 9
    optimistic: true
    step: 1
    restore_value: true

button:
  - platform: template
    name: Write Settings
    id: distance
    icon: mdi:cog-refresh
    entity_category: config
    on_press:
      # https://esphome.io/components/dfrobot_sen0395.html
      - dfrobot_sen0395.settings:
          detection_segments:
            - [0cm, 9m]
          sensitivity: !lambda return id(sensitivity).state;