esphome:
  name: "esphome-8-relay-board"
  friendly_name: ESPHome - 8CH Relay Board
  comment: "ESP32-WROOM-32E - 8CH Relay Board"

esp32:
  board: esp32dev

packages:
  base_general: !include .general-config.yaml

# wifi:
#   manual_ip:
#     static_ip: 20.20.30.X
#     gateway: 20.20.30.1
#     subnet: 255.255.255.0

status_led:
  pin:
    number: GPIO23

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      inverted: true
    name: Turn OFF GPIO
    on_press:
      if: 
        condition:
          and:
            - switch.is_on: relay1
            - switch.is_on: relay2
            - switch.is_on: relay3
            - switch.is_on: relay4
            - switch.is_on: relay5
            - switch.is_on: relay6
            - switch.is_on: relay7
            - switch.is_on: relay8
        then:
          - switch.turn_off: relay1
          - delay: 0.01s
          - switch.turn_off: relay2
          - delay: 0.01s
          - switch.turn_off: relay3
          - delay: 0.01s
          - switch.turn_off: relay4
          - delay: 0.01s
          - switch.turn_off: relay5
          - delay: 0.01s
          - switch.turn_off: relay6
          - delay: 0.01s
          - switch.turn_off: relay7
          - delay: 0.01s
          - switch.turn_off: relay8
          - switch.template.publish:
              id: master_switch
              state: OFF
        else: 
          - switch.turn_on: relay1
          - delay: 0.01s
          - switch.turn_on: relay2
          - delay: 0.01s
          - switch.turn_on: relay3
          - delay: 0.01s
          - switch.turn_on: relay4
          - delay: 0.01s
          - switch.turn_on: relay5
          - delay: 0.01s
          - switch.turn_on: relay6
          - delay: 0.01s
          - switch.turn_on: relay7
          - delay: 0.01s
          - switch.turn_on: relay8
          - switch.template.publish:
              id: master_switch
              state: ON

switch:
  - platform: gpio
    name: "Motor 1"
    pin: GPIO32
    id: relay1
    on_turn_on:
      if: 
        condition:
          and:
            - switch.is_on: relay1
            - switch.is_on: relay2
            - switch.is_on: relay3
            - switch.is_on: relay4
            - switch.is_on: relay5
            - switch.is_on: relay6
            - switch.is_on: relay7
            - switch.is_on: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: ON
    on_turn_off:
      if: 
        condition:
          and:
            - switch.is_off: relay1
            - switch.is_off: relay2
            - switch.is_off: relay3
            - switch.is_off: relay4
            - switch.is_off: relay5
            - switch.is_off: relay6
            - switch.is_off: relay7
            - switch.is_off: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: OFF

  - platform: gpio
    name: "Motor 2"
    pin: GPIO33
    id: relay2
    on_turn_on:
      if: 
        condition:
          and:
            - switch.is_on: relay1
            - switch.is_on: relay2
            - switch.is_on: relay3
            - switch.is_on: relay4
            - switch.is_on: relay5
            - switch.is_on: relay6
            - switch.is_on: relay7
            - switch.is_on: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: ON
    on_turn_off:
      if: 
        condition:
          and:
            - switch.is_off: relay1
            - switch.is_off: relay2
            - switch.is_off: relay3
            - switch.is_off: relay4
            - switch.is_off: relay5
            - switch.is_off: relay6
            - switch.is_off: relay7
            - switch.is_off: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: OFF

  - platform: gpio
    name: "Motor 3"
    pin: GPIO25
    id: relay3
    on_turn_on:
      if: 
        condition:
          and:
            - switch.is_on: relay1
            - switch.is_on: relay2
            - switch.is_on: relay3
            - switch.is_on: relay4
            - switch.is_on: relay5
            - switch.is_on: relay6
            - switch.is_on: relay7
            - switch.is_on: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: ON
    on_turn_off:
      if: 
        condition:
          and:
            - switch.is_off: relay1
            - switch.is_off: relay2
            - switch.is_off: relay3
            - switch.is_off: relay4
            - switch.is_off: relay5
            - switch.is_off: relay6
            - switch.is_off: relay7
            - switch.is_off: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: OFF

  - platform: gpio
    name: "Motor 4"
    pin: GPIO26
    id: relay4
    on_turn_on:
      if: 
        condition:
          and:
            - switch.is_on: relay1
            - switch.is_on: relay2
            - switch.is_on: relay3
            - switch.is_on: relay4
            - switch.is_on: relay5
            - switch.is_on: relay6
            - switch.is_on: relay7
            - switch.is_on: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: ON
    on_turn_off:
      if: 
        condition:
          and:
            - switch.is_off: relay1
            - switch.is_off: relay2
            - switch.is_off: relay3
            - switch.is_off: relay4
            - switch.is_off: relay5
            - switch.is_off: relay6
            - switch.is_off: relay7
            - switch.is_off: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: OFF

  - platform: gpio
    name: "Motor 5"
    pin: GPIO27
    id: relay5
    on_turn_on:
      if: 
        condition:
          and:
            - switch.is_on: relay1
            - switch.is_on: relay2
            - switch.is_on: relay3
            - switch.is_on: relay4
            - switch.is_on: relay5
            - switch.is_on: relay6
            - switch.is_on: relay7
            - switch.is_on: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: ON
    on_turn_off:
      if: 
        condition:
          and:
            - switch.is_off: relay1
            - switch.is_off: relay2
            - switch.is_off: relay3
            - switch.is_off: relay4
            - switch.is_off: relay5
            - switch.is_off: relay6
            - switch.is_off: relay7
            - switch.is_off: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: OFF

  - platform: gpio
    name: "Motor 6"
    pin: GPIO14
    id: relay6
    on_turn_on:
      if: 
        condition:
          and:
            - switch.is_on: relay1
            - switch.is_on: relay2
            - switch.is_on: relay3
            - switch.is_on: relay4
            - switch.is_on: relay5
            - switch.is_on: relay6
            - switch.is_on: relay7
            - switch.is_on: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: ON
    on_turn_off:
      if: 
        condition:
          and:
            - switch.is_off: relay1
            - switch.is_off: relay2
            - switch.is_off: relay3
            - switch.is_off: relay4
            - switch.is_off: relay5
            - switch.is_off: relay6
            - switch.is_off: relay7
            - switch.is_off: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: OFF

  - platform: gpio
    name: "Motor 7"
    pin: GPIO12
    id: relay7
    on_turn_on:
      if: 
        condition:
          and:
            - switch.is_on: relay1
            - switch.is_on: relay2
            - switch.is_on: relay3
            - switch.is_on: relay4
            - switch.is_on: relay5
            - switch.is_on: relay6
            - switch.is_on: relay7
            - switch.is_on: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: ON
    on_turn_off:
      if: 
        condition:
          and:
            - switch.is_off: relay1
            - switch.is_off: relay2
            - switch.is_off: relay3
            - switch.is_off: relay4
            - switch.is_off: relay5
            - switch.is_off: relay6
            - switch.is_off: relay7
            - switch.is_off: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: OFF

  - platform: gpio
    name: "Motor 8"
    pin: GPIO13
    id: relay8
    on_turn_on:
      if: 
        condition:
          and:
            - switch.is_on: relay1
            - switch.is_on: relay2
            - switch.is_on: relay3
            - switch.is_on: relay4
            - switch.is_on: relay5
            - switch.is_on: relay6
            - switch.is_on: relay7
            - switch.is_on: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: ON
    on_turn_off:
      if: 
        condition:
          and:
            - switch.is_off: relay1
            - switch.is_off: relay2
            - switch.is_off: relay3
            - switch.is_off: relay4
            - switch.is_off: relay5
            - switch.is_off: relay6
            - switch.is_off: relay7
            - switch.is_off: relay8
        then:
          - switch.template.publish:
              id: master_switch
              state: OFF

  - platform: template
    name: "Master Switch"
    id: master_switch
    turn_on_action:
      - then:
        - switch.turn_on: relay1
        - delay: 0.01s
        - switch.turn_on: relay2
        - delay: 0.01s
        - switch.turn_on: relay3
        - delay: 0.01s
        - switch.turn_on: relay4
        - delay: 0.01s
        - switch.turn_on: relay5
        - delay: 0.01s
        - switch.turn_on: relay6
        - delay: 0.01s
        - switch.turn_on: relay7
        - delay: 0.01s
        - switch.turn_on: relay8
        - switch.template.publish:
            id: master_switch
            state: ON
    turn_off_action:
      - then:
        - switch.turn_off: relay1
        - delay: 0.01s
        - switch.turn_off: relay2
        - delay: 0.01s
        - switch.turn_off: relay3
        - delay: 0.01s
        - switch.turn_off: relay4
        - delay: 0.01s
        - switch.turn_off: relay5
        - delay: 0.01s
        - switch.turn_off: relay6
        - delay: 0.01s
        - switch.turn_off: relay7
        - delay: 0.01s
        - switch.turn_off: relay8
        - switch.template.publish:
            id: master_switch
            state: OFF

