esphome:
  name: esphome-i2c-sensor-2024-7-1
  friendly_name: ESPHome - I2C Sensor
  comment: ESP32-C3-MINI-1-N4 V2024.7.1
  project:
    name: "RSVH.I2C_SENSOR"
    version: "2024.11.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: latest

packages:
  base_general: !include .general-config.yaml
  base_esp32: !include .esp32.yaml

# wifi:
#   manual_ip:
#     static_ip: 20.20.30.X
#     gateway: 20.20.30.1
#     subnet: 255.255.255.0

status_led:
  pin:
    number: GPIO2
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: 9
      inverted: true
    name: BOOT Button
    icon: mdi:radiobox-marked