substitutions:
  name: "esphome-double-switch"

esphome:
  name: "$name"
  friendly_name: "ESPHome - Double Switch"
  comment: "athom 2gang switch"
  min_version: 2024.6.0
  project:
    name: "Athom Technology.2Gang Switch"
    version: "v1.1.2"
  on_boot:
    - priority: 600
      then:
        - select.set_index:
            id: power_mode
            index: !lambda |-
                    return id(restore_mode)-1;
        - lambda: |-
              switch(id(restore_mode))
              {
              case 1:{
                      id(light1).turn_off();
                      id(light2).turn_off();
                      break;
                            }
              case 2:{
                      id(light1).turn_on();
                      id(light2).turn_on();
                      break;
                            }
              default:{
                      break;
                            }
              }

esp8266:
  board: esp8285
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

packages:
  base_general: !include .general-config.yaml

wifi:
  # manual_ip:
  #   static_ip: 10.10.30.X
  #   gateway: 10.10.30.1
  #   subnet: 255.255.255.0

globals:
  - id: restore_mode
    type: int
    restore_value: yes
    initial_value: "3"

select:
  - platform: template
    name: "Power On State"
    id: "power_mode"
    optimistic: true
    options:
      - Always Off
      - Always On
      - Restore Power Off State
    on_value:
      then:
        - lambda: |-
            id(restore_mode)=i+1;

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic

# Touch Buttons
  - platform: gpio
    pin:
      inverted: true
      number: GPIO3
      mode:
        input: true
        pullup: true
    name: "Button1"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

  - platform: gpio
    pin:
      inverted: true
      number: GPIO5
      mode:
        input: true
        pullup: true
    name: "Button2"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light2

button:
  - platform: factory_reset
    name: "Factory Reset"
    id: Reset
    entity_category: config

output:
# Relays
  - platform: gpio
    pin: GPIO13
    id: relay1
  - platform: gpio
    pin: GPIO4
    id: relay2

# Button LEDs (1.0 = Blue / 0.0 = Red)
  - platform: esp8266_pwm
    pin: GPIO14
    inverted: true
    id: led1
  - platform: esp8266_pwm
    pin: GPIO1
    inverted: true
    id: led2

light:
  - platform: status_led
    name: "Status LED"
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true

# Relays
  - platform: binary
    name: "Light1"
    id: light1
    output: relay1
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: light3
    on_turn_off:
      - light.turn_off: light3

  - platform: binary
    name: "Light2"
    id: light2
    output: relay2
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: light4
    on_turn_off:
      - light.turn_off: light4

# Button LEDs
  - platform: monochromatic
    name: "LED1"
    disabled_by_default: true
    id: light3
    output: led1
    default_transition_length: 500ms
  - platform: monochromatic
    name: "LED2"
    disabled_by_default: true
    id: light4
    output: led2
    default_transition_length: 500ms