logger:


web_server:
  version: 3
  port: 80

ota:
  platform: esphome
  password: !secret ota_password

api:
  reboot_timeout: 5min
  encryption:
    key: !secret api_encryption_key

esp32_ble_tracker:
    scan_parameters:
        active: true

bluetooth_proxy:
    active: true
    
time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: uptime
    id: uptime_sensor
    icon: mdi:clock-start
    internal: True
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

button:
  - platform: safe_mode
    name: "Safe Mode"
    internal: false
    icon: mdi:restart-alert

  - platform: restart
    id: restart_button
    name: "Restart"
    icon: mdi:restart

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

  - platform: template
    name: Uptime
    id: uptime_human
    icon: mdi:clock-start
    entity_category: diagnostic

  - platform: ethernet_info
    ip_address:
      name: IP Address
      icon: mdi:ip
    mac_address:
      name: MAC Address
      icon: mdi:ethernet

